{
 "title": "MQTT",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SoC",
   "type": "bargauge",
   "gridPos": { "h": 23, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "persistent Timeseries from Influx",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 3, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Current\" or r[\"_field\"] == \"StateOfCharge\" or r[\"_field\"] == \"Voltage\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"demo/battery\")"
    }
   ]
  },
  {
   "title": "hier könnte Ihre Werbung stehen",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 23, "w": 9, "x": 15, "y": 0 },
   "valueName": "current",
   "targets": [
    { "target": "metric", "type": "timeserie" }
   ]
  },
  {
   "title": "live stream data from MQTT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 3, "y": 12 },
   "targets": [
    { "queryText": "demo/battery" }
   ]
  }
 ]
}