version: "3.9"  
volumes:
    grafana_data:
configs:
    grafana_config:
        file: ./grafana.ini
services:
    grafana:
        build: .
        restart: unless-stopped
        ports:
            - "3000:3000"
        user: "472"
        configs:
            - source: grafana_config
              target: /etc/grafana/grafana.ini
        environment: 
            - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-worldmap-panel
        volumes:
            - grafana_data:/var/lib/grafana
        networks: 
            - backend   
    mariadb:
        image: mariadb
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: grafana
            MYSQL_USER: grafanauser
            MYSQL_PASSWORD: grafanaadmin
        networks: 
             - backend   
networks: 
    backend: