apiVersion: 1

deleteDatasources:
  - name: MQTT
    orgId: 1
  - name: HTTP-API
    orgId: 1
  - name: Prometheus
    orgId: 1
  - name: InfluxDB
    orgId: 1

datasources:
- name: HTTP-API
  type: grafana-simple-json-datasource
  enabled: true
  url: http://http-api:8080
  editable: true
  isDefault: false
- name: MQTT
  type: grafana-mqtt-datasource
  enabled: true
  access: direct
  editable: true
  isDefault: true
  secureJsonData:
    password: public
  jsonData:
    host: emqx-service
    port: 1883
    username: admin 
- name: Prometheus
  type: prometheus
  enabled: true
  url: http://prometheus-kube-prometheus-prometheus:9090
  default: false
  editable: true
  jsonData:
    timeInterval: 1s #custom timeInterval to manually change it in the dashboard
- name: InfluxDB
  type: influxdb
  editable: true
  access: proxy
  user: admin
  password: adminadmin
  url: http://influxdb-influxdb2:8086
  secureJsonData:
    token: INFLUXTOKEN
  jsonData:
    version: Flux
    organization: TRICERA
    defaultBucket: default
    tlsSkipVerify: true
- name: Loki
  type: loki
  enabled: true
  url: http://loki:3100
  editable: true
  isDefault: false