apiVersion: 1

deleteDatasources:
  - name: MQTT
    orgId: 1
  - name: Loki
    orgId: 1
  - name: InfluxDB
    orgId: 1
  - name: HTTP-API
    orgId: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  secureJsonData:
    token: 12345
  jsonData:
    version: Flux
    organization: TRICERA
    defaultBucket: default
    tlsSkipVerify: true
- name: Loki
  type: loki
  enabled: true
  url: http://loki:3100
  editable: true
  isDefault: false
- name: HTTP-API
  type: grafana-simple-json-datasource
  enabled: true
  url: http://http-api:8080
  editable: true
  isDefault: false
- name: MQTT
  type: grafana-mqtt-datasource
  enabled: true
  access: direct
  editable: true
  isDefault: true
  secureJsonData:
    password: public
  jsonData:
    host: emqx-service
    port: 1883
    username: admin 
    
  
